---
version: "3.3"

services:
  frontend:
    container_name: spring-task-client
    restart: always
    environment:
      - NODE_ENV=$NODE_ENV
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
    ports:
      - 4000:4000
    command: bash -c "yarn build && yarn start"

  db:
    container_name: spring-task-db
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=springdemo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  api:
    container_name: spring-task-api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/springdemo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./server/src:/api/src
    ports:
      - 8081:8081
    command: ./gradlew -t bootRun

  nginx:
    container_name: spring-task-proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - frontend
